config/routes.rb
Dumuzzi::Application.routes.draw do
  resources :protocols
  resources :queueds
  resources :state_changes
  resources :hosts_services do
    member do
      get :manual_test
      get :threads_test
    end
  end
  resources :services
  resources :hosts
  
  resources :domains do
    collection do
      post :monitored
    end
  end

  match '/terms' => 'static_pages#terms'
  match '/about' => 'static_pages#about'
  
  match '/signup' => 'users#new'
  resources :users
  
  match '/signin' => 'user_sessions#new'
  match '/signout' => 'user_sessions#destroy'
  resources :user_sessions
  
  match '/auth/:provider/callback' => 'authentications#create'
  match "/auth/failure" => 'authentications#failure'
  match "/auth/:provider" => 'authentications#blank'
  resources :authentications

  root :to => "home#index"
end

app/models/host.rb
class Host < ActiveRecord::Base
  before_create :generate_ids
  after_create :activate
  belongs_to :user
  belongs_to :domain
  belongs_to :status
  has_many :hosts_service
  has_many :services, :through => :hosts_service
  has_many :queueds
  has_many :tested, :class_name => 'queued', :primary_key => 'tester_id'
  has_many :status_changes
  
  def generate_ids
    uuid = UUID.new
    self.id = uuid.generate
    self.user_id = self.domain.user_id
  end
  
  def activate
    service_host_activate = Service.find_by_plugin('host_activate')
    HostsService.create(
      :domain_id => self.domain.id,
      :host_id => self.id,
      :service_id => service_host_activate.id,
      :user_id => self.user_id,
      :interval_id => 4,
      :description => service_host_activate.description,
      :status_id => -1,
      :monitor => true,
      :enabled => true
    )
  end
  
  def hostname
    "#{name}.#{domain.name}"
  end

  def gateway_alive?
    self.gateway = Rails.application.config.local_tester[:gateway]
    puts "[Network] Local tester id: #{hostname}"
    puts "[Network] Gateway: #{hostname}"
    puts "[Network] Testing connection..."
    unless Net::Ping::External.new(gateway).ping
      puts "[Network] Gateway error. Tests are disabled."
      self.gateway_state = false
      self.save
      return false
    else
      puts "[Network] Gateway OK. Tests are enabled."
      self.gateway_state = true
      self.save
      return true
    end
  end

  def status_changed?
    last_status = StatusChange.where(:host_id => self.id).limit(1).order('created_at DESC')
    unless last_status.empty?
      unless last_status.status_id == self.status_id
        true
      else
        false
      end
    else
      true
    end
  end
  
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  before_filter :init, :only => [:show, :edit, :update, :destroy]
    
  respond_to :html, :xml, :js, :json

  def index
    @hosts = Host.where(:domain_id => @domain.id, :is_domain_host => false).order('created_at ASC')
    
    respond_with @hosts
  end
    
  def show
    service_host_activate_id = Service.find_by_plugin('host_activate').id
    @hosts_service = HostsService.where("service_id <> '#{service_host_activate_id}'").where(:host_id => @host.id)
    
    respond_with @host
  end

  def new
    @host = Host.new(:domain_id => params[:domain_id])
    @domain = Domain.where(:id => @host.domain.id).first
    @domains = Domain.where(:id => @host.domain.id)

    respond_with @host
  end

  def edit
    @domain = Domain.where(:id => @host.domain.id).first
    @domains = Domain.where(:id => @host.domain.id)

    respond_with @host
  end

  def create
    @host = Host.new params[:host]
    @host.user_id = current_user.id

    if @host.save
      flash[:notice] = I18n.t :host_created
      respond_with @host
    else
      render :action => :new
    end
  end

  def update
    if @host.update_attributes params[:host]
      flash[:notice] = I18n.t :host_updated
      respond_with @host
    else
      render :action => :edit
    end
  end

  def destroy
    domain = @host.domain
    @host.destroy
    
    respond_with @host
  end
  
  protected
  def init
    @host = Host.where(:id => params[:id]).first
  end
    
end

app/helpers/hosts_helper.rb
module HostsHelper

end

app/views/hosts/_form.html.erb
<%= form_for(@host) do |f| %>
<div class="module_content">
  <% if @host.errors.any? %>
    <div id="error_explanation">
      <h4 class='alert_error'><%= pluralize(@host.errors.count, "error") %> prohibited this category from being saved:</h4>

      <ul>
      <% @host.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>

  <fieldset>
    <label><b><%= I18n.t :domain %></b></label>
    <%= f.collection_select(:domain_id, @domains, :id, :name, {:prompt => 'Selecione'} ) %>
  </fieldset>
  <fieldset>
    <label><b><%= I18n.t :name %></b></label><br />
    <%= f.text_field :name %>
  </fieldset>
  <fieldset>
    <label><b><%= I18n.t :description %></b></label><br />
    <%= f.text_area :description, :rows => 5  %>
  </fieldset>
  <fieldset>
    <label><b><%= I18n.t :allow_comments %></b></label>
    <%= f.check_box :allow_comments %>
  </fieldset>
  <fieldset>
    <label><b><%= I18n.t :send_alert %></b></label>
    <%= f.check_box :send_alert %>
  </fieldset>
  <fieldset>
    <label><b><%= I18n.t :share %></b></label>
    <%= f.check_box :share %>
  </fieldset>
  <fieldset>
    <label><b><%= I18n.t :monitor %></b></label>
    <%= f.check_box :monitor %>
  </fieldset>
  
</div>
  <div class="submit_link">
    <% if params[:action] == 'new' %>
      <%= f.submit I18n.t(:add_host) %>
    <% else %>
      <%= f.submit I18n.t(:edit_host) %>
    <% end %>
    <%= submit_tag(I18n.t(:reset), { :name => 'reset', :type => "reset" }) %>
    <%= link_to image_tag("/assets/icn_jump_back.png", :alt => I18n.t(:back), :title => I18n.t(:back), :border => 0), hosts_path %>
    <% if params[:action] == 'edit' %>
      <%= link_to image_tag("/assets/icn_folder.png", :alt => I18n.t(:show), :title => I18n.t(:show), :border => 0), @host %>
    <% end %>
  </div>
<% end %>

app/views/hosts/_index.html.erb
<div id="crud">
  <h3 class="tabs_involved"><%= I18n.t :listing_hosts %> <%= @domain.name %></h3>
  <div class="tab_container">
	  <div id="tab1" class="tab_content">
      <table class="tablesorter" cellspacing="0">
        <thead>
          <tr>
            <th><%= I18n.t :name %></th>
            <th><%= I18n.t :address %></th>
            <th><%= I18n.t :status %></th>
            <th><%= I18n.t :monitor %></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% @hosts.each do |host| %>
          <tr>
            <td><%= link_to host.name, host %></td>
            <td><%= host.address %></td>
            <td><%= host.status.name %></td>
            <td><%= show_icon host.monitor, "enabled", "disabled" %></td>
            <td><%= link_to image_tag("/assets/icn_edit_article.png", :alt => I18n.t(:edit), :title => I18n.t(:edit), :border => 0), edit_host_path(host) %></td>
            <td><%= button_to I18n.t(:delete), { :action => "destroy", :id => host.id }, :confirm => I18n.t(:are_you_sure), :method => :delete %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <br />

  <%= link_to I18n.t(:add_host), new_host_path(:domain_id => @domain.id) %>
</div>

app/views/hosts/edit.html.erb
<div id="new">
  <h3><%= I18n.t :editing_host %>  <%= @domains.name %></h3>
  <%= render 'form' %>
</div>

app/views/hosts/new.html.erb
<div id="new">
  <h3><%= I18n.t :adding_host %> <%= @domains.name %></h3>
  <%= render 'form' %>
</div>

app/views/hosts/show.html.erb
  <div id="show" >
    <h3><%= I18n.t :host %> <%= @host.hostname %> <%= link_to image_tag("/assets/icn_edit_article.png", :alt => I18n.t(:edit), :title => I18n.t(:edit), :border => 0), edit_host_path(@host) %> <%= link_to image_tag("/assets/icn_jump_back.png", :alt => I18n.t(:back), :title => I18n.t(:back), :border => 0), domain_path(@host.domain_id) %></h3>
    <div class="tab_container">
		  <div id="tab1" class="tab_content">
			  <table class="tablesorter" cellspacing="0">
          <tr> 
            <td><b><%= I18n.t :domain %></b></th>
            <td><%= @host.domain.name unless @host.domain.nil? %></td>            
			    </tr>
          <tr> 
            <td><b><%= I18n.t :name %></b></th>
            <td><%= @host.name %></td>            
			    </tr>
          <tr> 
            <td><b><%= I18n.t :address %></b></th>
            <td><%= @host.address %></td>            
			    </tr>
          <tr> 
            <td><b><%= I18n.t :description %></b></th>
            <td><%= @host.description %></td>            
			    </tr>
          <tr> 
            <td><b><%= I18n.t :allow_comments %></b></th>
            <td><%= show_icon @host.allow_comments, "enabled", "disabled" %></td>            
			    </tr>
          <tr> 
            <td><b><%= I18n.t :send_alert %></b></th>
            <td><%= show_icon @host.send_alert, "enabled", "disabled" %></td>            
			    </tr>
          <tr> 
            <td><b><%= I18n.t :share %></b></th>
            <td><%= show_icon @host.share, "enabled", "disabled" %></td>            
			    </tr>
          <tr> 
            <td><b><%= I18n.t :status %></b></th>
            <td><%= @host.status.name unless @host.status.nil? %></td>            
			    </tr>
          <tr> 
            <td><b><%= I18n.t :monitor %></b></th>
            <td><%= show_icon @host.monitor, "enabled", "disabled" %></td>            
			    </tr>
          <tr> 
            <td><b><%= I18n.t :enabled %></b></th>
            <td><%= show_icon @host.enabled, "enabled", "disabled" %></td>            
			    </tr>
        </table>
      </div>
    </div>
  </div>

  <%= render :partial => 'hosts_services/index' %>