config/routes.rb
Dumuzzi::Application.routes.draw do
  resources :protocols
  resources :queueds
  resources :state_changes
  resources :hosts_services do
    member do
      get :manual_test
      get :threads_test
    end
  end
  resources :services
  resources :hosts
  
  resources :domains do
    collection do
      post :monitored
    end
  end

  match '/terms' => 'static_pages#terms'
  match '/about' => 'static_pages#about'
  
  match '/signup' => 'users#new'
  resources :users
  
  match '/signin' => 'user_sessions#new'
  match '/signout' => 'user_sessions#destroy'
  resources :user_sessions
  
  match '/auth/:provider/callback' => 'authentications#create'
  match "/auth/failure" => 'authentications#failure'
  match "/auth/:provider" => 'authentications#blank'
  resources :authentications

  root :to => "home#index"
end

app/models/domain.rb
class Domain < ActiveRecord::Base
  before_create :generate_ids
  after_create :activate
  belongs_to :user
  has_many :hosts
  has_many :hosts_services
  belongs_to :status
  
  def generate_ids
    uuid = UUID.new
    self.id = uuid.generate
  end
  
  def activate
    host_activate = Service.find_by_plugin('domain_activate')
    interval = Interval.find_by_value('600')
    status = Status.find_by_name('Initialized')
    host = Host.create(
      :domain => self,
      :user => self.user,
      :name => '@', 
      :enabled => false,
      :monitor => true,
      :tester => false,
      :is_domain_host => true,
      :gateway => '0.0.0.0'
    )
    host.hosts_service.create(
      :domain_id => self,
      :host => host,
	    :service => host_activate,
    	:user => self.user,
	    :interval => interval,
	    :description =>	host_activate.description,
	    :status => status,
	    :monitor => true,
	    :enabled => true
	  )
    
  end
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController 
  before_filter :init, :only => [:show, :edit, :update, :destroy, :monitored]
  
  respond_to :html, :xml, :js, :json

  def index
    if current_user.is_admin
      @domains = Domain.order('created_at DESC')
    else
      @domains = Domain.where(:user_id => current_user.id).order('created_at DESC')
    end
    
    respond_with @domains
  end
    
  def show
    @hosts = Host.where(:domain_id => @domain.id, :is_domain_host => false).order('created_at ASC')
    
    respond_with @domain
  end

  def new
    @domain = Domain.new
    
    respond_with @domain
  end

  def edit
    respond_with @domain
  end

  def create
    @domain = Domain.new params[:domain]
    @domain.user_id = current_user.id
    @domain.monitor = false
    
    if @domain.save
      flash[:notice] = I18n.t :domain_created
      respond_with @domain
    else
      render :action => :new
    end
  end

  def update
    if @domain.update_attributes params[:domain]
      flash[:notice] = I18n.t :domain_updated
      respond_with @domain
    else
      render :action => :edit
    end
  end

  def destroy
    @domain.destroy
    
    respond_with @domain
  end
  
  def monitored
    if @domain.monitor == false
      if current_user.email.nil?
        @user = current_user
      else
        @domain.monitor = true
      end
    
    else
      @domain.monitor = false      
    end
    
    @domain.save
    respond_with @domain
  end
  
  protected
  def init
    @domain = Domain.where(:id => params[:id]).first
  end
    
end

app/helpers/domains_helper.rb
module DomainsHelper

end

app/views/domains/_form.html.erb
<%= form_for(@domain) do |f| %>
<div class="module_content">
  <% if @domain.errors.any? %>
    <div id="error_explanation">
      <h4 class='alert_error'><%= pluralize(@domain.errors.count, "error") %> prohibited this category from being saved:</h4>

      <ul>
      <% @domain.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <label><b><%= I18n.t :name %></b></label><br />
    <%= f.text_field :name %>
  </fieldset>
  <fieldset>
    <label><b><%= I18n.t :description %></b></label><br />
    <%= f.text_area :description, :rows => 5 %>
  </fieldset>
  <fieldset>
    <label><b><%= I18n.t :allow_comments %></b></label>
    <%= f.check_box :allow_comments %>
  </fieldset>
  <fieldset>
    <label><b><%= I18n.t :send_alert %></b></label>
    <%= f.check_box :send_alert %>
  </fieldset>
  <fieldset>
    <label><b><%= I18n.t :share %></b></label>
    <%= f.check_box :share %>
  </fieldset>
  
</div>
  <div class="submit_link">
    <% if params[:action] == 'new' %>
      <%= f.submit I18n.t(:add_domain) %>
    <% else %>
      <%= f.submit I18n.t(:edit_domain) %>
    <% end %>
    <%= submit_tag(I18n.t(:reset), { :name => 'reset', :type => "reset" }) %>
    <%= link_to image_tag("/assets/icn_jump_back.png", :alt => I18n.t(:back), :title => I18n.t(:back), :border => 0), domains_path %>
    <% if params[:action] == 'edit' %>
      <%= link_to image_tag("/assets/icn_folder.png", :alt => I18n.t(:show), :title => I18n.t(:show), :border => 0), @domain %>
    <% end %>
  </div>
<% end %>

app/views/domains/edit.html.erb
<div id="new">
  <h3><%= I18n.t :editing_domain %> <%= @domain.name %></h3>
  <%= render 'form' %>
</div>

app/views/domains/index.html.erb
<%= javascript_include_tag "application.js" %>
<div id="crud">
  <h3 class="tabs_involved"><%= I18n.t :my_domains %></h3>
  <div class="tab_container">
	  <div id="tab1" class="tab_content">
      <table class="tablesorter" cellspacing="0">
        <thead>
          <tr>
            <th><%= I18n.t :name %></th>
            <th><%= I18n.t :address %></th>
            <th><%= I18n.t :status %></th>
            <th><%= I18n.t :monitor %></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% @domains.each do |domain| %>
          <tr>
            <td><%= link_to domain.name, domain %></td>
            <td><%= domain.address %></td>
            <td><%= domain.status.name unless domain.status.nil? %></td>
            <td id="domain_<%= domain.id %>_monitor"><%= link_to show_icon(domain.monitor, "enabled", "disabled"), "javascript:void(0);", :onclick => "change_state('#{domain.id}', 'domains/monitored')" %></td>
            <td><%= link_to image_tag("icn_edit_article.png", :alt => I18n.t(:edit), :title => I18n.t(:edit), :border => 0), edit_domain_path(domain) %></td>
            <td><%= button_to I18n.t(:delete), { :action => "destroy", :id => domain.id }, :confirm => I18n.t(:are_you_sure), :method => :delete %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <br />

  <%= link_to I18n.t(:add_domain), new_domain_path %>
</div>

app/views/domains/monitored.js.erb
<% if @user.nil? %>
  var monitored = 'domains/monitored';
  var domain_id = '<%= @domain.id %>';
  var domain = $("#domain_"+ domain_id +"_monitor");
  domain.empty();
  domain.append(''+
  '<a onclick="change_state(domain_id, monitored)" href="javascript:void(0);">'+
    '<%= show_icon(@domain.monitor, "enabled", "disabled") %>'+
  '</a>');
<% else %>
  $('article').append(""+
  '<h4 class="alert_error">Cadastre o seu email para poder receber alertas</h4>'+
  '<div class="user-form">'+
    '<h1><%= I18n.t :register_email %></h1>'+
    '<%= form_for(@user) do |f| %>'+
      '<p>'+
        '<%= f.label :email %><br />'+
        '<%= f.text_field :email %>'+
      '</p>'+
      '<p><%= f.submit %></p>'+
    '<% end %>'+
  '</div>');
<% end %>

app/views/domains/new.html.erb
<div id="new">  
  <h3><%= I18n.t :adding_domain %></h3>
  <%= render 'form' %>
</div>

app/views/domains/show.html.erb
  <div id="show">
	  <h3><%= I18n.t :domain %> <%= @domain.name %> <%= link_to image_tag("icn_edit_article.png", :alt => I18n.t(:edit), :title => I18n.t(:edit), :border => 0), edit_domain_path(@domain) %>  <%= link_to image_tag("icn_jump_back.png", :alt => I18n.t(:back), :title => I18n.t(:back), :border => 0), domains_path %></h3>
    <div class="tab_container">
		  <div id="tab1" class="tab_content">
			  <table class="tablesorter" cellspacing="0">
          <tr> 
            <td><b><%= I18n.t :name %></b></th>
            <td><%= @domain.name %></td>            
			    </tr>
          <tr> 
            <td><b><%= I18n.t :address %></b></th>
            <td><%= @domain.address %></td>            
			    </tr>
          <tr> 
            <td><b><%= I18n.t :description %></b></th>
            <td><%= @domain.description %></td>            
			    </tr>
          <tr> 
            <td><b><%= I18n.t :allow_comments %></b></th>
            <td><%= show_icon @domain.allow_comments, "enabled", "disabled" %></td>            
			    </tr>
          <tr> 
            <td><b><%= I18n.t :send_alert %></b></th>
            <td><%= show_icon @domain.send_alert, "enabled", "disabled" %></td>            
			    </tr>
          <tr> 
            <td><b><%= I18n.t :share %></b></th>
            <td><%= show_icon @domain.share, "enabled", "disabled" %></td>            
			    </tr>
          <tr> 
            <td><b><%= I18n.t :status %></b></th>
            <td><%= @domain.status.name unless @domain.status.nil? %></td>
			    </tr>
          <tr> 
            <td><b><%= I18n.t :monitor %></b></th>
            <td><%= show_icon @domain.monitor, "enabled", "disabled" %></td>            
			    </tr>
          <tr> 
            <td><b><%= I18n.t :enabled %></b></th>
            <td><%= show_icon @domain.enabled, "enabled", "disabled" %></td>            
			    </tr>
        </table>
      </div>
    </div>
  </div>
  <%= render :partial => 'hosts/index' %>