config/routes.rb
Dumuzzi::Application.routes.draw do
  resources :protocols
  resources :queueds
  resources :state_changes
  resources :hosts_services do
    member do
      get :manual_test
      get :threads_test
    end
  end
  resources :services
  resources :hosts
  
  resources :domains do
    collection do
      post :monitored
    end
  end

  match '/terms' => 'static_pages#terms'
  match '/about' => 'static_pages#about'
  
  match '/signup' => 'users#new'
  resources :users
  
  match '/signin' => 'user_sessions#new'
  match '/signout' => 'user_sessions#destroy'
  resources :user_sessions
  
  match '/auth/:provider/callback' => 'authentications#create'
  match "/auth/failure" => 'authentications#failure'
  match "/auth/:provider" => 'authentications#blank'
  resources :authentications

  root :to => "home#index"
end

app/models/queued.rb
require 'net/ping'
require 'net/http'

class Queued < ActiveRecord::Base
  before_create :generate_ids
  belongs_to :host
  belongs_to :tester, :class_name => 'Host'
  belongs_to :service
  belongs_to :hosts_service
  belongs_to :interval
  belongs_to :status
  
  def generate_ids
    uuid = UUID.new
    self.id = uuid.generate
  end

  def new_status
    last_status = StatusChange.where(:hosts_service_id => self.hosts_service_id).limit(1).order('created_at DESC')[0]
    if last_status.nil?
      last_status_id = -1
    else
      last_status_id = last_status.status_id
    end
    
    status_change = StatusChange.new
    status_change.host = self.host
    status_change.hosts_service = self.hosts_service
    status_change.tester_id = self.tester_id
    status_change.service = self.service
    status_change.interval = self.interval
    status_change.from_status_id = last_status_id
    status_change.to_status_id = self.hosts_service.status_id
    status_change.make_subject
    status_change.make_description
    status_change.status = self.hosts_service.status
    status_change.save
    
    if self.host.send_alert
      DumuzziMailer.warning_message(status_change).deliver
    end unless self.host.domain.send_alert == false
  end

  def host_activate
    if internal_ping
      puts "Activated host #{host.hostname}"
      hash = Socket.gethostbyname(host.hostname)[3]
      ip = "%d.%d.%d.%d" % [hash[0].ord, hash[1].ord, hash[2].ord, hash[3].ord]
      host.address = ip
      host.enabled = true
      host.status_id = -2
      hosts_service.status_id = -2
      hosts_service.save
      host.save
      return true
    else
      puts "Error activating host #{host.hostname}"
      host.address = '0.0.0.0'
      host.enabled = false
      host.status_id = 2
      hosts_service.status_id = 2
      hosts_service.save
      host.save
      return false
    end
  end

  def domain_activate
    if internal_domain_ping
      puts "Activated domain #{host.domain.name}"
      hash = Socket.gethostbyname(host.domain.name)[3]
      ip = "%d.%d.%d.%d" % [hash[0].ord, hash[1].ord, hash[2].ord, hash[3].ord]
      host.domain.address = ip
      host.domain.enabled = true
      host.domain.status_id = -2
      host.domain.save
      return true
    else
      puts "Error activating domain #{host.domain.name}"
      host.domain.address = '0.0.0.0'
      host.domain.enabled = false    
      host.domain.status_id = 2
      host.domain.save
      return false
    end
  end

  def internal_domain_ping
    puts ">>>> #{host.domain.name}"
    Service::internal_ping(host.domain.name)
  end

  def internal_ping
    Service::internal_ping(host.hostname)
  end

  def internal_http_
    hostname = "#{host.hostname}"
    Net::Ping::HTTP.new(hostname).ping
  end

  def internal_http
    hostname = "#{host.hostname}"
    begin
      Net::HTTP.start(hostname) do |http|
        response = http.get('/')
        if not response.code.match(/200/)
          puts "Web Server down or not resonding: #{response.code} #{response.message}"
        else
          true
        end
      end
    rescue SocketError => socket_error
      puts "Error Connecting To Web: #{socket_error}"
    rescue TimeoutError => timeout_error
      puts "Web connection timed out: #{timeout_error}"
    end    
  end

end

app/controllers/queueds_controller.rb
class QueuedsController < ApplicationController
  before_filter :init, :only => [:show, :edit, :update, :destroy]
  
  respond_to :html, :xml, :js, :json

  def index
    @queueds = Queued.order 'created_at DESC'
    
    respond_with @queueds
  end
    
  def show
    respond_with @queued
  end

  def new
    @queued = Queued.new
    
    respond_with @queued
  end

  def edit
    respond_with @queued
  end

  def create
    @queued = Queued.new params[:queued]
    
    if @queued.save
      flash[:notice] = I18n.t :queued_created
      respond_with @queued
    else
      render :action => :new
    end
  end

  def update
    if @queued.update_attributes params[:queued]
      flash[:notice] = I18n.t :queued_updated
      respond_with @queued
    else
      render :action => :edit
    end
  end

  def destroy
    @queued.destroy
    
    respond_with @queued
  end
  
  protected
  def init
    @queued = Queued.where(:id => params[:id]).first
  end
    
end

app/helpers/queueds_helper.rb
module QueuedsHelper

end

app/views/queueds/_form.html.erb
<%= form_for(@queued) do |f| %>
<div class="module_content">
  <% if @queued.errors.any? %>
    <div id="error_explanation">
      <h4 class='alert_error'><%= pluralize(@queued.errors.count, "error") %> prohibited this category from being saved:</h4>

      <ul>
      <% @queued.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
</div>
<footer>
  <div class="submit_link">
    <% if params[:action] == 'new' %>
      <%= f.submit I18n.t(:add_queued) %>
    <% else %>
      <%= f.submit I18n.t(:edit_queued) %>
    <% end %>
    <%= submit_tag(I18n.t(:reset), { :name => 'reset', :type => "reset" }) %>
    <%= link_to image_tag("/assets/icn_jump_back.png", :alt => I18n.t(:back), :title => I18n.t(:back)), queueds_path %>
    <% if params[:action] == 'edit' %>
      <%= link_to image_tag("/assets/icn_folder.png", :alt => I18n.t(:show), :title => I18n.t(:show)), @queued %>
    <% end %>
  </div>
</footer>
<% end %>

app/views/queueds/edit.html.erb
<article class="module width_full">
  <header>
    <h3><%= I18n.t :editing_queued %></h3>
  </header>
  <%= render 'form' %>
</article>

app/views/queueds/index.html.erb
<article class="module width_3_quarter">
  <header>
    <h3 class="tabs_involved"><%= I18n.t :listing_queueds %></h3>
  </header>

  <div class="tab_container">
	  <div id="tab1" class="tab_content">
      <table class="tablesorter" cellspacing="0">
        <thead>
          <tr>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% @queueds.each do |queued| %>
          <tr>
            <td></td>
            <td><%= link_to image_tag("/assets/icn_folder.png", :alt => I18n.t(:show), :title => I18n.t(:show)), queued %></td>
            <td><%= link_to image_tag("/assets/icn_edit_article.png", :alt => I18n.t(:edit), :title => I18n.t(:edit)), edit_queued_path(queued) %></td>
            <td><%= button_to I18n.t(:delete), { :action => "destroy", :id => queued.id }, :confirm => I18n.t(:are_you_sure), :method => :delete %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <br />

  <%= link_to I18n.t(:new_queued), new_queued_path %>
</article>

app/views/queueds/new.html.erb
<article class="module width_full">
  <header>
    <h3><%= I18n.t :new_queued %></h3>
  </header>
  <%= render 'form' %>
</article>

app/views/queueds/show.html.erb
  <article class="module width_full">
	  <header><h3><%= I18n.t :showing %></h3></header>
    <div class="tab_container">
		  <div id="tab1" class="tab_content">
			  <table class="tablesorter" cellspacing="0">
        </table>
      </div>
    </div>

    <footer>
      <div class="submit_link">
        <%= link_to image_tag("/assets/icn_edit_article.png", :alt => I18n.t(:edit), :title => I18n.t(:edit)), edit_queued_path(@queued) %> 
        <%= link_to image_tag("/assets/icn_jump_back.png", :alt => I18n.t(:back), :title => I18n.t(:back)), queueds_path %>
      </div>
    </footer>
  </article>